version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000" # Exporta a porta 3000 para o host
    environment:
      - REACT_APP_API_URL=http://backend:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  db:
    image: postgres:15
    # Porta 5432 não precisa ser exposta ao host
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  playwright:
    image: mcr.microsoft.com/playwright:v1.39.0-focal
    # Porta 9222 não precisa ser exposta ao host
    entrypoint: ["tail", "-f", "/dev/null"]
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
