services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    # volumes:
      # - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      target: development
    ports:
      - "8080:8080"  
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
      NODE_ENV: development
      DEBUG: "*"
    depends_on:
      db:
        condition: service_healthy
    command: ["npm", "run", "start:dev"]

  frontend:
    build:
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080
    depends_on:
      - backend
    command: ["npm", "run", "start:dev"]

  e2e:
    build:
      context: ./e2e
    depends_on:
      - frontend
      - backend
    command: ["sh", "-c", "npm run test || tail -f /dev/null"]

# volumes:
#   db_data: