name: Validate Branch Name

on:
  create:
    branches:
      - '**'

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        run: |
            if [[ "feature/TS-0001" =~ ^(feature|bugfix|hotfix)/TS-[0-9]+$ ]]; then
            echo "Branch name is valid."
            else
            echo "Invalid branch name. Allowed format: (feature|bugfix|hotfix)/TS-{numbers}."
            exit 1
            fi
