name: Continuous Integration

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build-backend-image:
        name: Build Backend Image
        runs-on: ubuntu-latest
        outputs:
            docker-image: ${{ steps.docker_meta.outputs.tags }}
        permissions: 
          contents: read
          pull-requests: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup up Docker Buildx
              uses: docker/setup-buildx-action@v2
              
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:  
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Docker metadata
              id: docker_meta
              uses: docker/metadata-action@v4
              with:
                images: ${{ secrets.DOCKER_USERNAME }}/backend
                tags: ${{ github.event_name == 'push' && github.ref_name == 'main' && 'production' || 'buildstage' }}_${{ github.head_ref || github.ref_name }}_${{ github.sha }}
                labels: |
                  org.example.team=QA Engineer
                  org.example.project=TestShip
                  org.example.environment=${{ github.event_name == 'push' && 'Production' || 'Development' }}
                  org.example.event=${{ github.event_name }}
                  org.example.merge=${{ github.event_name == 'push' && 'true' || 'false' }}
                  org.example.pull_request=${{ github.event_name == 'pull_request' && 'true' || 'false' }}

            - name: Docker build
              uses: docker/build-push-action@v2
              with: 
                context: ./backend
                cache-from: type=gha
                cache-to: type=gha,mode=max
                push: true
                tags: $${{ steps.docker_meta.outputs.tags }}
                labels: ${{ steps.docker_meta.outputs.labels }}
                target: ${{ github.event_name == 'pull_request' && 'build' || 'production' }}
                build-args: |
                  NODE_ENV=${{ github.event_name == 'push' && 'production' || 'development' }}

            - name: Update Pull Request with Docker Info
              if: ${{ github.event_name == 'pull_request' }}
              uses: actions/github-script@v6
              with:
                script: |
                  const prNumber = context.payload.pull_request.number;
                  const dockerTags = `${{ steps.docker_meta.outputs.tags }}`;
                  const dockerLabels = `${{ steps.docker_meta.outputs.labels }}`;
                  const bodyUpdate = `
                  ### Docker Build Information
                  - **Tags:** ${dockerTags}
                  - **Labels:** ${dockerLabels}
                  `;
                  const { data: pullRequest } = await github.pulls.get({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: prNumber,
                  });
                  const updatedBody = `${pullRequest.body || ''}\n\n${bodyUpdate}`;
                  await github.pulls.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: prNumber,
                    body: updatedBody,
                  });
   
    CVE-scan:
      name: CVE Scan in Docker
      runs-on: ubuntu-latest
      needs: build-backend-image
      if: ${{ github.event_name == 'pull_request' }}

      permissions:
        contents: read
        security-events: write

      steps: 
        - name: Login to Docker hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Run Trivy for CVEs (all vulnerabilities - no blocking)
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: ${{ secrets.DOCKER_USERNAME }}/backend:${{ needs.build-backend-image.outputs.docker-image }}
            format: 'table'
            exit-code: 0
        
        - name: Run Trivy for CVEs (CRITICAL, HIGH - blocking)
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: ${{ secrets.DOCKER_USERNAME }}/backend:${{ needs.build-backend-image.outputs.docker-image }}
            format: 'sarif'
            exit-code: 1
            ignore-unfixed: 'true'
            severity: 'CRITICAL,HIGH'
            output: 'trivy-scan.sarif'
        
            # image-ref: ${{ secrets.DOCKER_USERNAME }}/backend:${{ needs.build-backend-image.outputs.docker-image }}
            # format: ${{ github.event_name == 'push' && github.ref_name == 'main' && 'sarif' || 'table' }}
            # exit-code: ${{ github.event_name == 'push' && github.ref_name == 'main' && 1 || 0 }}
            # ignore-unfixed: ${{ github.event_name == 'push' && github.ref_name == 'main' && 'true' || 'false' }}
            # severity: ${{ github.event_name == 'push' && github.ref_name == 'main' && 'CRITICAL,HIGH' || 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL' }}
            # output: ${{ github.event_name == 'push' && github.ref_name == 'main' && 'trivy-scan.sarif' || '' }}
        
        - name: Upload SARIF to GitHub Code Scanning
          if: always()
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: trivy-scan.sarif
        
    unit-testing:
      name: Unit Testing in Docker
      runs-on: ubuntu-latest
      needs: build-backend-image    
      if: ${{ github.event_name == 'pull_request' }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Login to Docker hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
       
    integration-testing:
      name: Integration Testing in Docker
      runs-on: ubuntu-latest
      needs: build-backend-image
      if: ${{ github.event_name == 'pull_request' }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run integration tests
          run: |
            docker run --rm ${{ secrets.DOCKER_USERNAME }}/backend:${{ steps.docker_meta.outputs.tags }} npm test -- --watchAll=false --testPathPattern=integration-tests

    e2e-testing:
      name: E2E Testing in Docker
      runs-on: ubuntu-latest
      needs: build-backend-image
      if: ${{ github.event_name == 'pull_request' }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run e2e tests
          run: |
            docker run --rm ${{ secrets.DOCKER_USERNAME }}/backend:${{ steps.docker_meta.outputs.tags }} npm test -- --watchAll=false --testPathPattern=e2e-tests
